### ISSUE TITLE
training scripts mismatch with models

### ISSUE THREAD

**Issue by xiedidan** [Alfo5123/Variational-Sparse-Coding#3]
Hi guys,
I'm trying to train vsc with the command you given in readme:
```
python train-vsc.py --dataset mnist --epochs 20 --report-interval 4 --lr 0.001 --alpha 0.2 --hidden-size 2000,2000 --latent-size 800
```
But it looks some mismatch exists:
```
VSC Baseline Experiments

Using cuda device...
Loading mnist dataset...
Done!

Traceback (most recent call last):
  File "train-vsc.py", line 31, in <module>
    args.normalize)
TypeError: __init__() missing 1 required positional argument: 'flatten'
```

For vae I got mismatch again:
```
python train-vae.py --dataset mnist --epochs 500 --report-interval 50 --lr 0.01
```
```
VAE Baseline Experiments

Using cuda device...
Loading mnist dataset...
Done!

Traceback (most recent call last):
  File "train-vae.py", line 30, in <module>
    normalize=args.normalize)
  File "/home/xd/project/Variational-Sparse-Coding/src/models/vae.py", line 58, in __init__
    self.model = VAE(self.input_sz, self.hidden_sz, latent_sz).to(device)
  File "/home/xd/project/Variational-Sparse-Coding/src/models/vae.py", line 15, in __init__
    self.fc1 = nn.Linear(input_sz, hidden_szs[0])
  File "/home/xd/anaconda3/envs/vsc/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 72, in __init__
    self.weight = Parameter(torch.Tensor(out_features, in_features))
TypeError: new(): argument 'size' must be tuple of ints, but found element of type tuple at pos 2
```

I'm using master branch and I know that I could fix these problems by myself since this is an open source project. Just let you guys be awared of that... And could you kindly push the updated model if it's possible.

**Comment by Alfo5123** [comment]
Hi @xiedidan thanks for your comment. Certainly, since the time we coded some functionalities in PyTorch have been updated and we have not actively maintained the code. With respect to the 'flatten' parameter, I think we used it for some experiments but now it should be deleted.

**Comment by xiedidan** [comment]
Thanks. I'll look into the code and fix this. This is a good project and I learned a lot from it.
